import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  const mopopEvent = await prisma.event.create({
    data: {
      title: 'Seattle MoPOP Scavenger Hunt',
      slug: 'seattle-mopop',
      description: 'A scavenger hunt at the Museum of Pop Culture in Seattle.',
      date: new Date('2025-10-26T10:00:00Z'),
      questions: {
        create: [
          {
            title: 'Seahawks player jersey',
            content: 'Name a Seahawks player whose jersey is on display.',
            type: 'text',
            expectedAnswer: null,
            hintEnabled: false,
          },
          {
            title: 'Jimi\'s outfits',
            slug: 'jimi-outfits',
            content: 'Name one of Jimi\'s outfits on display.',
            type: 'text',
            expectedAnswer: 'The Butterfly Costume or the Vintage Velvet Vestment Cape.',
            hintEnabled: false,
          },
          {
            title: 'Jimi at Woodstock',
            slug: 'jimi-woodstock',
            content: 'What song did Jimi play on the White Stratocoaster at Woodstock?',
            type: 'text',
            expectedAnswer: '"The Star-Spangled Banner".',
            hintEnabled: false,
          },
          {
            title: 'Jimi\'s Westerner Hat',
            slug: 'jimi-westerner-hat',
            content: 'Find Jimi\'s Westerner Hat and name a place he wore it.',
            type: 'text',
            expectedAnswer: null,
            hintEnabled: false,
          },
          {
            title: 'Jimi\'s Studio',
            slug: 'jimi-studio',
            content: 'What was the name of Jimi\'s Studio?',
            type: 'text',
            expectedAnswer: 'Electric Lady Studio.',
            hintEnabled: false,
          },
          {
            title: 'Video game companies',
            slug: 'video-game-companies',
            content: 'How many video game companies are located in the Puget Sound area?',
            type: 'text',
            expectedAnswer: 'Over 300.',
            hintEnabled: false,
          },
          {
            title: 'Women video game creators',
            slug: 'women-video-game-creators',
            content: 'What percent of women are video game creators?',
            type: 'text',
            expectedAnswer: '30%.',
            hintEnabled: false,
          },
          {
            title: 'Musician loved guitar',
            slug: 'musician-loved-guitar',
            content: 'Which musician loved their guitar so much they pictured it on their business cards?',
            type: 'text',
            expectedAnswer: 'Howlin\' Wolf.',
            hintEnabled: false,
          },
          {
            title: 'Washington native Taylor GC8',
            slug: 'washington-native-taylor-gc8',
            content: 'Which Washington native played her Taylor GC8 in her video for "The Story"?',
            type: 'text',
            expectedAnswer: 'Brandi Carlile.',
            hintEnabled: false,
          },
          {
            title: 'Oldest instrument',
            slug: 'oldest-instrument',
            content: 'What is the oldest instrument in this exhibition?',
            type: 'text',
            expectedAnswer: '1900 Wolfram Triumph.',
            hintEnabled: false,
          },
          {
            title: 'Play a chord',
            slug: 'play-a-chord',
            content: 'Play a chord on the piano and write down which chord you learned.',
            type: 'text',
            expectedAnswer: null,
            hintEnabled: false,
          },
          {
            title: 'Guitar tutorial song',
            slug: 'guitar-tutorial-song',
            content: 'What song do they teach you for the guitar tutorial?',
            type: 'text',
            expectedAnswer: null,
            hintEnabled: false,
          },
          {
            title: 'Instrument without touching',
            slug: 'instrument-without-touching',
            content: 'What instrument in Sound Lab can you play without touching? (Hint: It\'s in the back of Sound Lab)',
            type: 'text',
            expectedAnswer: 'Beamz.',
            hintEnabled: false,
          },
          {
            title: 'Rihanna music video',
            slug: 'rihanna-music-video',
            content: 'In what music video did Rihanna wear the bodysuit on display?',
            type: 'text',
            expectedAnswer: '"Rude Boy".',
            hintEnabled: false,
          },
          {
            title: 'Lizzo\'s catsuit designer',
            slug: 'lizzo-catsuit-designer',
            content: 'Who designed Lizzo\'s catsuit?',
            type: 'text',
            expectedAnswer: 'Seth Pratts.',
            hintEnabled: false,
          },
          {
            title: 'Original lightsabers',
            slug: 'original-lightsabers',
            content: 'What were the original lightsabers made of?',
            type: 'text',
            expectedAnswer: 'Antique camera flash parts.',
            hintEnabled: false,
          },
          {
            title: 'Star Wars movie Darth Vader suit',
            slug: 'star-wars-movie-darth-vader-suit',
            content: 'What is the title of the Star Wars movie the Darth Vader suit is from?',
            type: 'text',
            expectedAnswer: 'The Empire Strikes Back.',
            hintEnabled: false,
          },
          {
            title: 'Seahawks Superbowl win',
            slug: 'seahawks-superbowl-win',
            content: 'What Superbowl did the Seattle Seahawks win their Lombardi trophy? (year and/or number accepted)',
            type: 'text',
            expectedAnswer: 'Super Bowl XLVIII 2014.',
            hintEnabled: false,
          },
          {
            title: 'Rebel soldier uniform planet',
            slug: 'rebel-soldier-uniform-planet',
            content: 'The Rebel soldier uniform is from the battle on what planet?',
            type: 'text',
            expectedAnswer: 'Hoth.',
            hintEnabled: false,
          },
          {
            title: 'Ghostbusters artifacts',
            slug: 'ghostbusters-artifacts',
            content: 'Name one of the three artifacts, on display in Infinite Worlds, from the movie Ghostbusters.',
            type: 'text',
            expectedAnswer: 'Proton Pack, Parking Sign, or Ghost Trap.',
            hintEnabled: false,
          },
          {
            title: 'Viper pilot suit character',
            slug: 'viper-pilot-suit-character',
            content: 'The Viper pilot suit and helmet on display in Infinite Worlds was worn by which character from the TV series Battlestar Galactica?',
            type: 'text',
            expectedAnswer: 'Starbuck.',
            hintEnabled: false,
          },
          {
            title: 'Character archetype quiz',
            slug: 'character-archetype-quiz',
            content: 'Take the character archetype quiz and name a character with your archetype or a similar archetype.',
            type: 'text',
            expectedAnswer: null,
            hintEnabled: false,
          },
          {
            title: 'Cowardly lion costume',
            slug: 'cowardly-lion-costume',
            content: 'True or False: The cowardly lion costume from The Wizard of Oz was made of real lion pelts.',
            type: 'text',
            expectedAnswer: null,
            hintEnabled: false,
          },
          {
            title: 'Harry Potter scarf house',
            slug: 'harry-potter-scarf-house',
            content: 'What house is the scarf in the Harry Potter display from?',
            type: 'text',
            expectedAnswer: 'Gryffindor.',
            hintEnabled: false,
          },
          {
            title: 'Iconic music video zombie costume',
            slug: 'iconic-music-video-zombie-costume',
            content: 'What iconic music video has a zombie costume on display?',
            type: 'text',
            expectedAnswer: '"Thriller".',
            hintEnabled: false,
          },
          {
            title: 'Axe movie',
            slug: 'axe-movie',
            content: 'What movie is the axe from?',
            type: 'text',
            expectedAnswer: 'The Shining.',
            hintEnabled: false,
          },
          {
            title: 'Morticia Addams dress wearer',
            slug: 'morticia-addams-dress-wearer',
            content: 'Who wore the Morticia Addams dress?',
            type: 'text',
            expectedAnswer: 'Anjelica Huston.',
            hintEnabled: false,
          },
          {
            title: 'Car over ticketing counter movie',
            slug: 'car-over-ticketing-counter-movie',
            content: 'What movie is the car suspended over the main ticketing counter from?',
            type: 'text',
            expectedAnswer: 'Blade Runner (1982).',
            hintEnabled: false,
          },
          {
            title: 'Invisible museum artifact',
            slug: 'invisible-museum-artifact',
            content: 'What is the only artifact in the museum that you can\'t see?',
            type: 'text',
            expectedAnswer: 'Harry Potter\'s Invisibility Cloak and Air Guitar.',
            hintEnabled: false,
          },
        ],
      },
    },
  });
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
