name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --only=production

      - name: Cache Next.js build
        uses: actions/cache@v4
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-build-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-build-${{ hashFiles('**/package-lock.json') }}-
            ${{ runner.os }}-nextjs-build-

      - name: Build
        run: npm run build

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure gcloud
        run: gcloud config set project simple-scavenger-hunt

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy simple-scavenger-hunt \
            --source . \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --memory 1Gi \
            --cpu 1 \
            --max-instances 10

      - name: Set environment variables
        run: |
          gcloud run services update simple-scavenger-hunt \
            --region us-central1 \
            --set-env-vars \
            DATABASE_URL=${{ secrets.DATABASE_URL }},\
            ADMIN_USERNAME=${{ secrets.ADMIN_USERNAME }},\
            ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }},\
            NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }},\
            NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }},\
            OPENROUTER_API_KEY=${{ secrets.OPENROUTER_API_KEY }}

      - name: Output service URL
        run: |
          SERVICE_URL=$(gcloud run services describe simple-scavenger-hunt --region us-central1 --format="value(status.url)")
          echo "Service URL: $SERVICE_URL"